name: 'release'

on:
    push:
        branches:
            - 'master'

jobs:
    pre-release:
        name: Version
        runs-on: 'ubuntu-latest'
        steps:
            - uses: actions/checkout@v2
            - if: 'contains(github.event.head_commit.message,"#patch")'
            - run: npm version patch
            - if: 'contains(github.event.head_commit.message,"#minor")'
            - run: npm version minor
            - if: 'contains(github.event.head_commit.message,"#major")'
            - run: npm version major
        
    release:
        name: 'Release'
        runs-on: 'ubuntu-latest'

        steps:
            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  automatic_release_tag: 'latest'
                  prerelease: false
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm ci
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
