name: 'release'

on:
    push:
        branches:
            - 'master'

jobs:
    release:
        name: 'Release'
        runs-on: 'ubuntu-latest'
        if: "!contains(github.event.head_commit.message,'#no-release')"

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: |
                  git config --global user.email "ci@create-react-embeddable.com"
                  git config --global user.name "CI"

            - name: patch
              id: patch
              if: "contains(github.event.head_commit.message,'#patch')"
              run: npm version patch

            - name: minor
              id: minor
              if: "contains(github.event.head_commit.message,'#minor')"
              run: npm version minor

            - name: major
              id: major
              if: "contains(github.event.head_commit.message,'#major')"
              run: npm version major

            - name: get-npm-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@master

            - name: FF devel
              uses: peter-evans/create-pull-request@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: ci bump \#no-release \#update-devel
                  title: Bump to ${{ steps.package-version.outputs.current-version }}

              uses: devmasx/merge-branch@v1.1.0
              with:
                  type: now
                  label_name: 'ci'
                  target_branch: 'devel'

            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  automatic_release_tag: '${{ steps.package-version.outputs.current-version }}'
                  prerelease: false
            - run: npm ci
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
