name: 'release'

on:
    push:
        branches:
            - 'master'

jobs:
    patch:
        name: patch
        runs-on: 'ubuntu-latest'
        if: "contains(github.event.head_commit.message,'#patch')"
        steps:
            - uses: actions/checkout@v2
            - run: npm version patch
              
    minor:
        name: minor
        runs-on: 'ubuntu-latest'
        if: "contains(github.event.head_commit.message,'#minor')"
        steps:
            - uses: actions/checkout@v2
            - run: npm version minor  
              
    major:
        name: major
        runs-on: 'ubuntu-latest'
        if: "contains(github.event.head_commit.message,'#major')"
        steps:
            - uses: actions/checkout@v2
            - run: npm version major  
                        
    release:
        name: 'Release'
        runs-on: 'ubuntu-latest'

        steps:
            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  automatic_release_tag: 'latest'
                  prerelease: false
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm ci
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
